CapitalCompass/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('financeapp.urls')),
    path('accounts/', include('registration.backends.default.urls')), 
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),

]

financeapp/urls.py
from django.urls import path 
from financeapp import views
app_name = 'financeapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('profile/', views.profile, name='profile'),
    
    path('overview/', views.overview, name='overview'),
    path('help/', views.help_page, name='help'),
    
    #path('select_budget/<int:budget_id>/', views.select_budget, name='select_budget'),

  
     
    #path for account.intro
   
    path('accounts/', views.account_list, name='account_list'),
    path('accounts/add/', views.add_account, name='add_account'),
    path('accounts/edit/', views.edit_account, name='edit_account'),
    path('accounts/delete/<int:account_id>/', views.delete_account, name='delete_account'),
    path('accounts/add_money/', views.add_money_to_account, name='add_money_to_account'),
   


    
    
    path('logout-and-signup/', views.logout_and_signup, name='logout_and_signup'),
    
    path('create-budget/', views.create_budget, name='create_budget'),
    path('budgets/', views.budget_list, name='budget_list'),
    path('budgets/delete/<int:budget_id>/', views.delete_budget, name='delete_budget'),
    
    #path for zero_based budget
    path('budgets/zero_based/<int:budget_id>/', views.zero_based_page, name='zero_based_page'), 
    path('budgets/zero-based/<int:budget_id>/<int:year>/<int:month>/', views.zero_based_page, name='zero_based_page_with_date'),
    path('budgets/zero_based/<int:budget_id>/add_category/', views.add_zero_based_category, name='add_zero_category'),
    path('budgets/zero_based/<int:budget_id>/edit_category/', views.edit_zero_based_category, name='edit_zero_category'),
    path('budgets/zero_based/<int:budget_id>/add_expense/', views.add_zero_based_expense, name='add_zero_expense'),
    path('budgets/zero_based/<int:budget_id>/edit_expense/', views.edit_zero_based_expense, name='edit_zero_expense'),
    
    path('budgets/zero_based/<int:budget_id>/delete_category/', views.delete_zero_based_category, name='delete_zero_category'),
    path('budgets/zero_based/<int:budget_id>/delete_expense/', views.delete_zero_based_expense, name='delete_zero_expense'),

    #path for 50.30.20 budget
    path('budgets/fifty_thirty_twenty/<int:budget_id>/', views.fifty_thirty_twenty_page, name='fifty_thirty_twenty_page'),
    path('budgets/fifty_thirty_twenty/<int:budget_id>/<int:year>/<int:month>/', views.fifty_thirty_twenty_page, name='fifty_thirty_twenty_page_with_date'),
    path('budgets/fifty_thirty_twenty/<int:budget_id>/add_expense/', views.add_fifty_thirty_twenty_expense, name='add_fifty_thirty_twenty_expense'),
    path('budgets/fifty_thirty_twenty/<int:budget_id>/edit_expense/', views.edit_fifty_thirty_twenty_expense, name='edit_fifty_thirty_twenty_expense'),
    path('budgets/fifty_thirty_twenty/<int:budget_id>/delete_50_expense/', views.delete_50_expense, name='delete_expense'),
    path('budgets/fifty_thirty_twenty/<int:budget_id>/delete_30_expense/', views.edit_fifty_thirty_twenty_category, name='edit_category'),
    
    path('load-sidebar-content/<int:budget_id>/', views.load_sidebar_content_with_budget, name='load_sidebar_content_with_budget'),
    path('load-sidebar-content/', views.load_sidebar_content_without_budget, name='load_sidebar_content_without_budget'),
    
    path('transactions/', views.transaction_list, name='transactions'),
    path('transactions/add/', views.add_transaction, name='add_transaction'),
    path('transactions/edit/', views.edit_transaction, name='edit_transaction'),
    path ('transactions/delete/', views.delete_transaction, name='delete_transaction'), 
    
    path('analysis/', views.financial_analysis, name='financial_analysis'),
    path('analysis/<int:year>/<int:month>/', views.financial_analysis, name='financial_analysis_with_date'),
    
    path('contact/', views.contact, name='contact'),
    #path('contactLog/', views.contactLoggedIn, name='contactLog'),
    path('account_support/', views.account_support, name='account_support'),
    #path('get-categories-for-date/', views.get_categories_for_date, name='get_categories_for_date'),
    
    # Other URL patterns...
    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
    path('create-link-token/', views.create_link_token, name='create_link_token'),
   # path('exchange-public-token/', views.exchange_public_token, name='exchange_public_token'),
   # path('get-balance/<int:account_id>/', views.get_balance, name='get_balance'),
   path('create-and-link-account/', views.create_and_link_account, name='create_and_link_account'),
   path('refresh-account-transaction/', views.refresh_account_and_transactions, name='refresh_account_and_transactions'),
    
]

financeapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver
from decimal import Decimal

import datetime

# USer Profile Model
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    last_accessed_budget = models.ForeignKey('Budget', on_delete=models.SET_NULL, null=True, blank=True)
    def __str__(self):
        return self.user.username

#Budget Model
class Budget(models.Model):
    BUDGET_TYPES = [
        ('zero_based', 'Zero-Based'),
        ('fifty_thirty_twenty', '50/30/20'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='budgets')
    budget_name = models.CharField(max_length=100)
    budget_type = models.CharField(max_length=20, choices=BUDGET_TYPES)
    month = models.DateField(auto_now_add=True)  # Add month field
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
   # balance_initialized = models.BooleanField(default=False)

    # Meta class to ensure that the budget name is unique for each user
    class Meta:
        unique_together = ('user', 'budget_name')

    def __str__(self):
        return f"{self.budget_name} ({self.get_budget_type_display()}) - {self.user.username}"

    # Update the assigned amount for each category in the 50/30/20 budget
    def update_fifty_thirty_twenty_categories(self):
        if self.budget_type == 'fifty_thirty_twenty':
            total_balance = sum(account.balance for account in self.accounts.all())
            total_balance_float = float(total_balance)  # Convert Decimal to float
            for category in self.fifty_thirty_twenty_categories.all():
                if category.name == 'Needs':
                    category.assigned_amount = Decimal(0.5 * total_balance_float)
                elif category.name == 'Wants':
                    category.assigned_amount = Decimal(0.3 * total_balance_float)
                else:
                    category.assigned_amount = Decimal(0.2 * total_balance_float)
                category.save()



class Account(models.Model):
    ACCOUNT_TYPES = [
       ('CHECKING', 'checking'),
       ('SAVINGS', 'savings'),
       # ('CREDIT', 'credit'),  # Commented out or use if necessary
       ('CASH', 'cash'),
       ('OTHER', 'other'),
    ]
    budget = models.ForeignKey(Budget, on_delete=models.CASCADE, related_name='accounts')
    account_name = models.CharField(max_length=100)
    account_type = models.CharField(max_length=20, choices=ACCOUNT_TYPES, blank=True, default='OTHER')  # Ensure choices is added
    custom_account_type = models.CharField(max_length=100, blank=True, null=True)
    balance = models.DecimalField(max_digits=15, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    plaid_enabled = models.BooleanField(default=False)

    def __str__(self):
        # Add a debug print to check the account type value
        print(f"Debug: account_type={self.account_type}")
        if self.account_type == 'OTHER' and self.custom_account_type:
            return f"{self.account_name} ({self.custom_account_type}) - {self.budget.budget_name}"
        return f"{self.account_name} ({self.get_account_type_display()}) - {self.budget.budget_name}"

    def save(self, *args, **kwargs):
        if self.custom_account_type and self.account_type not in dict(self.ACCOUNT_TYPES).keys():
            self.account_type = 'OTHER'
        super().save(*args, **kwargs)
        self.budget.update_fifty_thirty_twenty_categories()


class PlaidAccount(models.Model):
    account = models.OneToOneField(Account, on_delete=models.CASCADE, related_name='plaid_account')
    access_token = models.CharField(max_length=100)
    item_id = models.CharField(max_length=100)
    plaid_account_id = models.CharField(max_length=100)  # Plaid's account ID for this specific account
    institution_name = models.CharField(max_length=100)
    
    def __str__(self):
        return f"{self.institution_name} - {self.account.account_name}"

# Signal to create an initial transaction when an account is created manually. if plaid is not enabled
@receiver(post_save, sender=Account)
def create_initial_transaction(sender, instance, created, **kwargs):
    if created and not instance.plaid_enabled:
        Transaction.objects.create(
            account=instance,
            date=timezone.now(),
            description=f"Initial balance for {instance.account_name}",
            inflow=instance.balance,
            outflow=0,
            created_by_account=True,
        )

#Base Category
class BaseCategory(models.Model):
    assigned_amount = models.DecimalField(max_digits=10, decimal_places=2)
    month = models.DateField(default=datetime.date.today().replace(day=1))


    class Meta:
        abstract = True
    def __str__(self):
        return self.name

    @property
    def activity(self):
        return sum(expense.spent for expense in self.expenses.all())

    @property
    def available(self):
        return self.assigned_amount - self.activity

    @property
    def expenses_assigned_amount_total(self):
        return sum(expense.assigned_amount for expense in self.expenses.all())
    '''
    def save(self, *args, **kwargs):
        if self.assigned_amount_total > self.assigned_amount:
            self.assigned_amount = self.assigned_amount_total
        super().save(*args, **kwargs)
    '''

 #50.30.20 Models implementation
# 50/30/20 Category Model
class FiftyThirtyTwentyCategory(BaseCategory):
    CATEGORY_CHOICES = [
        ('Needs', 'Needs'),
        ('Wants', 'Wants'),
        ('Savings', 'Savings'),
    ]

    budget = models.ForeignKey(Budget, on_delete=models.CASCADE, related_name='fifty_thirty_twenty_categories')
    name = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    is_recurring = models.BooleanField(default=True)  # New field to indicate if category is occuring
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
   # month_only = models.DateField(default=datetime.date.today().replace(day=1))


    def __str__(self):
        return f"{self.name} - {self.budget.budget_name} ({self.month.strftime('%B %Y')})"

    class Meta:
        unique_together = ('budget', 'name', 'month')

@receiver(post_save, sender=Budget)
def create_fifty_thirty_twenty_categories(sender, instance, created, **kwargs):
    if created and instance.budget_type == 'fifty_thirty_twenty':
        categories = ['Needs', 'Wants', 'Savings']
        for name in categories:
            FiftyThirtyTwentyCategory.objects.create(
                budget=instance,
                name=name,
                assigned_amount=0.0,
                month=instance.month

            )


#Zero Based Models implementation
class ZeroBasedCategory(BaseCategory):
    budget = models.ForeignKey(Budget, on_delete=models.CASCADE, related_name='zero_based_categories')
    name = models.CharField(max_length=100)
   # month_only = models.DateField(default=datetime.date.today().replace(day=1))
    is_recurring = models.BooleanField(default=False)
    class Meta:
        unique_together = ('budget', 'name', 'month')

    def __str__(self):
        return self.name
    
# Signal to create a default category when a Zero-Based Budget is created
@receiver(post_save, sender=Budget)
def create_default_zero_based_category(sender, instance, created, **kwargs):
    if created and instance.budget_type == 'zero_based':
        # Check if a default category already exists to avoid duplication
        if not ZeroBasedCategory.objects.filter(budget=instance, name='General Expenses').exists():
            ZeroBasedCategory.objects.create(
                budget=instance,
                name='General Expenses',  # Use the chosen name here
                assigned_amount=Decimal(0.00),  # Default assigned amount, can be modified as needed
            )


class Expense(models.Model):
    fifty_30_twenty_category = models.ForeignKey(FiftyThirtyTwentyCategory, on_delete=models.CASCADE, related_name='expenses', null=True, blank=True)
    category = models.ForeignKey(ZeroBasedCategory, on_delete=models.CASCADE, related_name='expenses', null=True, blank=True)
    description = models.CharField(max_length=255, blank=True, null=True)
    date = models.DateField(auto_now_add=True)
    is_recurring = models.BooleanField(default=False)  # New field to indicate if the expense is recurring
    month_only = models.DateField(default=datetime.date.today().replace(day=1))

    assigned_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    spent = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    class Meta:
        unique_together = ('fifty_30_twenty_category', 'description', 'month_only'), ('category', 'description', 'month_only')


    def __str__(self):
        return f"{self.assigned_amount} - {self.description}"
    @property
    def available(self):
        return self.assigned_amount - self.spent

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # Update the category's assigned amount if necessary
        if self.category:
            self.category.save()
        if self.fifty_30_twenty_category:
            self.fifty_30_twenty_category.save()
            
    def delete(self, *args, **kwargs):
        # Update the account balance based on the transaction before deleting it
         # Reverse the effect of all transactions associated with this expense
        for transaction in self.transactions.all():
            # If it's an outflow transaction, add the amount back to the account
            if transaction.outflow > 0:
                transaction.account.balance += transaction.outflow
            # Save the updated account balance

templates/financeapp/accounts.html
{% extends 'financeapp/loggedin_base.html' %}
{% load static %}
{% block title_block %} Accounts - CapitalCompass {% endblock %}

{% block head_block %}
<link rel="stylesheet" href="{% static 'styles/accounts.css' %}">
<script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js"></script>
{% endblock %}

{% block body_block %}
<main>
    <section class="accounts-overview">
        <h1>Accounts Overview</h1>
        <div id="summary">
            <p>Total Balance: £<span id="total-balance">{{ total_balance }}</span></p>
        </div>
        <div class="add-button-class">
             <button class="btn btn-primary" onclick="showAddAccountForm()">Add Account Manually</button>
             <button class="btn btn-primary" id="link-button" onclick="showPlaid()">Link Your Bank Account</button>
        </div>
        <div class="account-list">
            <ul>
                {% for account in accounts %}
                <li class="account-box">
                    <div class="account-header">
                        <div class="account-type">
                            {% if account.plaid_account %} 
                                {{ account.custom_account_type }} 
                            {% else %} 
                                {{ account.account_type }}
                            {% endif %} - 
                            {% if account.plaid_account %}
                                Linked Account 
                                <button class="btn btn-sm btn-outline-secondary" onclick="refreshAccount('{{ account.id }}')">Refresh</button>
                            {% else %}
                                Manually Added
                            {% endif %}
                        </div>
                        <div class="dropdown">
                            <button class="dropbtn">⋮</button>
                            <div class="dropdown-content">
                                <form method="get" action="{% url 'financeapp:transactions' %}">
                                    <input type="hidden" name="account_id" value="{{ account.id }}">
                                    <button type="submit">View Transactions</button>
                                </form>
                                <button onclick="showEditAccountForm({{ account.id }}, '{{ account.account_name }}', '{{ account.account_type }}')">Edit</button>
                                {% if not account.plaid_account %}
                                    <button onclick="showAddMoneyForm({{ account.id }})">Add Money</button>
                                {% endif %}
                                <form method="get" action="{% url 'financeapp:delete_account' account.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn-danger">Delete</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="account-details">
                        {{ account.account_name }}: Current Balance: £{{ account.balance }}
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
        
    </section>
</main>


<!-- Add Account Modal -->
<div id="add-account-form-modal" class="modal">
    <div class="modal-content">
        <span class="close-button" onclick="closeAddAccountForm()">&times;</span>
        <h2>New Account</h2>
        <form method="post" action="{% url 'financeapp:add_account' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_account_name">Account Name:</label>
                <input type="text" name="account_name" id="id_account_name" required>
            </div>
            <div class="form-group">
                <label for="id_balance">Balance:</label>
                <input type="number" name="balance" id="id_balance" required>
            </div>
            <div class="form-group">
                <label for="id_account_type">Account Type:</label>
                <select name="account_type" id="id_account_type">
                    <option value="CHECKING">Checking</option>
                    <option value="SAVINGS">Savings</option>
                    <option value="CASH">Cash</option>
                </select>
            </div>
            <div class="form-group submit-btn">
                <button type="submit" class="btn btn-primary">Add Account</button>
                <button type="button" class="btn btn-secondary" onclick="closeAddAccountForm()">Cancel</button>
            </div>
        </form>
    </div>    
</div>

<!-- Edit Account Modal -->
<div id="edit-account-form" class="modal">
    <div class="modal-content">
        <span class="close-button" onclick="closeEditAccountForm()">&times;</span>
        <h2>Edit Account</h2>
        <form method="post" action="{% url 'financeapp:edit_account' %}">
            {% csrf_token %}
            <input type="hidden" name="account_id" id="edit-account-id">
            <div class="form-group">
                <label for="edit-account-name">Account Name:</label>
                <input type="text" name="account_name" id="edit-account-name" required>
            </div>
            <div class="form-group">
                <label for="edit-account-type">Account Type:</label>
                <select name="account_type" id="edit-account-type">
                    <option value="CHECKING">Checking</option>
                    <option value="SAVINGS">Savings</option>
                    <option value="CASH">Cash</option>
                </select>
            </div>
            <div class="form-group submit-btn">
                <button type="submit" class="btn btn-primary">Save Changes</button>
                <button type="button" class="btn btn-secondary" onclick="closeEditAccountForm()">Cancel</button>
            </div>
        </form>
    </div>
</div>

<!-- Add Money to Account Modal -->
<div id="add-money-form-modal" class="modal">
    <div class="modal-content">
        <span class="close-button" onclick="closeAddMoneyForm()">&times;</span>
        <h2>Add Money to Account</h2>
        <form method="post" action="{% url 'financeapp:add_money_to_account' %}">
            {% csrf_token %}
            <input type="hidden" name="account_id" id="add-money-account-id">
            <div class="form-group">
                <label for="id_amount">Amount:</label>
                <input type="number" name="amount" id="id_amount" required>
            </div>
            <div class="form-group submit-btn">
                <button type="submit" class="btn btn-primary">Add Money</button>
                <button type="button" class="btn btn-secondary" onclick="closeAddMoneyForm()">Cancel</button>
            </div>
        </form>
    </div>
</div>

<script>
    // Function to show the Add Account Modal
    function showAddAccountForm() {
        document.getElementById('add-account-form-modal').style.display = 'flex';
    }
    function closeAddAccountForm() {
        document.getElementById('add-account-form-modal').style.display = 'none';
    }

    // Function to show the Edit Account Modal
    function showEditAccountForm(accountId, accountName, accountType) {
        document.getElementById('edit-account-id').value = accountId;
        document.getElementById('edit-account-name').value = accountName;
        document.getElementById('edit-account-type').value = accountType;
        document.getElementById('edit-account-form').style.display = 'flex';
    }
    function closeEditAccountForm() {
        document.getElementById('edit-account-form').style.display = 'none';
    }

    // Function to show the Add Money Modal
    function showAddMoneyForm(accountId) {
        document.getElementById('add-money-account-id').value = accountId;
        document.getElementById('add-money-form-modal').style.display = 'flex';
    }
    function closeAddMoneyForm() {
        document.getElementById('add-money-form-modal').style.display = 'none';
    }

    // Plaid Link integration
    function showPlaid() {
        const handler = Plaid.create({
            token: '{{ link_token }}',
            onSuccess: function(public_token, metadata) {
                // Send the public token to the server
                fetch('/create-and-link-account/', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': '{{ csrf_token }}',
                    },
                    body: JSON.stringify({ public_token: public_token })
                }).then(response => response.json())
                .then(data => {
                    console.log(data); // Add this line
                    if (data.success) {

                        // Reload the page to show the new account
                        location.reload();
                    } else {
                        alert('There was an error linking your account');
                    }
                });
            },
            onExit: function(err, metadata) {
                if (err) {
                    console.error('Link exited with error:', err);
                }
            },
        });
        handler.open();
    }
    // Function to refresh a specific account
function refreshAccount() {
    fetch(`/refresh-account-transaction/`, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': '{{ csrf_token }}',
        }
    }).then(response => response.json())
    .then(data => {
        if (data.success) {
            // Reload the page to reflect updated account information
            location.reload();
        } else {
            alert('There was an error refreshing the account.');
        }
    }).catch(error => {
        console.error('Error refreshing account:', error);
        alert('An error occurred while refreshing the account.');
    });
}


    // Initialize modals visibility on page load
    window.onload = function() {
        closeAddAccountForm();
        closeEditAccountForm();
        closeAddMoneyForm();
    }
</script>
{% endblock %}

templates/financeapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title_block %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'styles/HomeStyles.css' %}">

    {% block head_block %} {% endblock %}
</head>
<body>
    <header>
        <div class="div-logo">
        <div class="logo">CapitalCompass</div>
        </div>
        <nav>
            <ul class="nav-left">
                <li><a href="{% url 'financeapp:index' %}">Home</a></li>
                <li><a href="{% url 'financeapp:about' %}">About us</a></li>
                <li><a href="{% url 'financeapp:contact'%}">Contact us</a></li>
            </ul>
            <ul class="nav-right">
              {% if user.is_authenticated %} 
              <li class="auth"><a href="{% url 'auth_login' %}">Login</a></li>
              <li class="auth"><a href="{% url 'financeapp:logout_and_signup' %}">Sign up</a></li> 
              {% else %} 
                <li class="auth"><a href="{% url 'auth_login' %}">Login</a></li>
                <li class="auth"><a href="{% url 'registration_register' %}">Sign up</a></li>
              {% endif %}
            </ul>
        </nav>
    </header>

    {% block body_block %}{% endblock %}

    {% block footer_block %}
    <footer>
        <div class="footer-content">
            <a href="{% url 'financeapp:about' %}">About us</a>
            <a href="{% url 'financeapp:contact'%}">Contact us anytime </a>
            <p>&copy; 2024 CapitalCompass. All rights reserved.</p>
            <p>Device Mockup created from <a href="https://deviceframes.com/templates/macbook-pro-m1-14" target="_blank">MacBook Pro mockups</a></p>
           
           <!-- <div class="social-media-icons">[Social Media Icons]</div>
            <div class="contact-info">
                <p>Contact: email@example.com</p>
                <p>Phone: (123) 456-7890</p>
            </div> -->
        </div>
    </footer>
    {% endblock %}

</body>
</html>

templates/financeapp/loggedin_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title_block %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'styles/application.css' %}">

    {% block head_block %}{% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <div class="sidebar">
        <div id="dynamic-sidebar-content">
            <!-- Default content or loading spinner -->
    
        </div>
        <nav>
            <ul class="nav-bottom">
                <li><a href="{% url 'financeapp:budget_list' %}">Your Budgets</a></li>
                <li><a href="{% url 'financeapp:account_support' %}">Account Support</a></li>
                <li><a href="{% url 'financeapp:help' %}">Help and Support</a></li>
                <li><a href="{% url 'financeapp:profile' %}">Profile</a></li>
                <li><a href="{% url 'auth_logout' %}?next={% url 'financeapp:index' %}">Log out</a></li>
            </ul>
        </nav>
    </div>
    {% block body_block %}{% endblock %}
    
    <script>
        function loadSidebarContent(budgetId) {
            var url = budgetId ? '{% url "financeapp:load_sidebar_content_with_budget" 0 %}'.replace('0', budgetId) : '{% url "financeapp:load_sidebar_content_without_budget" %}';
            $.ajax({
                url: url,
                type: 'GET',
                success: function(response) {
                    if (response.sidebar_content) {
                        $('#dynamic-sidebar-content').html(response.sidebar_content);
                    } else {
                        console.error('Failed to load sidebar content');
                    }
                },
                error: function(xhr, status, error) {
                    console.error(error);
                }
            });
        }
    
        function loadSelectedBudgetSidebar() {
            var selectedBudgetId = {{ request.session.selected_budget_id|default:"null" }};
            loadSidebarContent(selectedBudgetId);
        }
    
        $(document).ready(function() {
            loadSelectedBudgetSidebar();
        
        });
    </script>
    
</body>
</html>

templates/financeapp/sidebar_dynamic_content.html
<!-- sidebar_dynamic_content.html -->
{% if budget %}
    <div class="logo">
        {{ budget.budget_name }} - CapitalCompass
    </div>
    <nav>
        <ul class="nav-top">
            {% if budget.budget_type == 'zero_based' %}
                <li><a href="{% url 'financeapp:zero_based_page' budget.id %}">{{ budget.budget_name }} Budget </a></li>
            {% elif budget.budget_type == 'fifty_thirty_twenty' %}
                <li><a href="{% url 'financeapp:fifty_thirty_twenty_page' budget.id %}">{{ budget.budget_name }} Budget </a></li>
            {% endif %}
            <li><a href="{% url 'financeapp:financial_analysis' %}">Financial Analysis</a></li>
            <li><a href="{% url 'financeapp:account_list' %}">Accounts</a></li>
            <li><a href="{% url 'financeapp:transactions' %}">Transactions</a></li>
            <li><a href="{% url 'financeapp:overview' %}">Overview</a></li>
        </ul>
    </nav>
{% else %}
    <div class="logo">
        CapitalCompass
    </div>
    <nav>
        <ul class="nav-top">
            <li><a href="{% url 'financeapp:overview' %}">Overview</a></li>
            <li><a href="{% url 'financeapp:create_budget' %}">Create Budget</a></li>
        </ul>
    </nav>
{% endif %}